# Generated by Django 5.2.5 on 2025-08-15 17:33

from django.db import migrations

def populate_exercises(apps, schema_editor):
    Exercise = apps.get_model('app', 'Exercise')
    exercises = [
        # Chest
        {'name': 'Bench Press', 'category': 'Chest'},
        {'name': 'Incline Bench Press', 'category': 'Chest'},
        {'name': 'Dumbbell Flyes', 'category': 'Chest'},
        {'name': 'Push-ups', 'category': 'Chest'},
        # Back
        {'name': 'Pull-ups', 'category': 'Back'},
        {'name': 'Deadlift', 'category': 'Back'},
        {'name': 'Bent Over Row', 'category': 'Back'},
        {'name': 'Lat Pulldown', 'category': 'Back'},
        # Legs
        {'name': 'Squat', 'category': 'Legs'},
        {'name': 'Leg Press', 'category': 'Legs'},
        {'name': 'Lunges', 'category': 'Legs'},
        {'name': 'Calf Raises', 'category': 'Legs'},
        # Shoulders
        {'name': 'Overhead Press', 'category': 'Shoulders'},
        {'name': 'Lateral Raises', 'category': 'Shoulders'},
        {'name': 'Front Raises', 'category': 'Shoulders'},
        {'name': 'Shrugs', 'category': 'Shoulders'},
        # Arms
        {'name': 'Bicep Curls', 'category': 'Arms'},
        {'name': 'Tricep Dips', 'category': 'Arms'},
        {'name': 'Hammer Curls', 'category': 'Arms'},
        {'name': 'Tricep Pushdowns', 'category': 'Arms'},
        # Abs
        {'name': 'Crunches', 'category': 'Abs'},
        {'name': 'Plank', 'category': 'Abs'},
        {'name': 'Leg Raises', 'category': 'Abs'},
        {'name': 'Russian Twists', 'category': 'Abs'},
        # Cardio
        {'name': 'Running', 'category': 'Cardio'},
        {'name': 'Cycling', 'category': 'Cardio'},
        {'name': 'Jumping Jacks', 'category': 'Cardio'},
        {'name': 'Burpees', 'category': 'Cardio'},
    ]
    for exercise_data in exercises:
        Exercise.objects.create(**exercise_data)

def delete_exercises(apps, schema_editor):
    Exercise = apps.get_model('app', 'Exercise')
    Exercise.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_exercises, delete_exercises),
    ]
